### ISSUE TITLE
ComputeEntryWisePerturbationExpectation: Greater uncertainty with smaller b values

### ISSUE THREAD

**Issue by rockowd** [dkoslicki/PressPurtCoreAlg#20]
In specifying `input_b` in `ComputeEntryWisePerturbationExpectation`, the larger the b-value, the less error?!?

```
PreProsMatrix <- PreprocessMatrix(input_file = infile, output_folder = NULL, max_bound = 10, threads = 2)
Entrywise2 <- ComputeEntryWisePerturbationExpectation(PreProsMatrix = PreProsMatrix, 
                                                     distribution_type="truncnorm", 
                                                     input_a=0, input_b=-0.1, threads=1)
Entrywise2$expected_num_switch
GenerateEntryWiseFigures(EntryWise=Entrywise2, 
                         all_numswitch_plots = TRUE)

Entrywise3 <- ComputeEntryWisePerturbationExpectation(PreProsMatrix = PreProsMatrix, 
                                                     distribution_type="truncnorm", 
                                                     input_a=0, input_b=-10, threads=1)
Entrywise3$expected_num_switch
GenerateEntryWiseFigures(EntryWise=Entrywise3, 
                         all_numswitch_plots = TRUE)
```

**Comment by dkoslicki** [comment]
According to the [documentation on this function](http://math.oregonstate.edu/~koslickd/PressPurtCoreAlg/html/Scripts.html#computeentrywiseperturbationexpectation-py):
`` -b First parameter to the distribution you choose. For truncnorm, this is the variance. Using a negative value indicates you want the standard deviation to be the length of the interval divided by the absolute value of the input parameter.
`` 
So using -0.1 would result in a standard deviation of `10*interval_length`. I assume that this may cause a problem due to the `num_switch` functions only being defined on the interval of stability.

@rockowd does the error go down progressively when you make `-b` negative, but progressively larger (eg. -1, -.5, -.1, -.01)? If so, that would confirm this behavior. And a fix would be to require that the value of `-b`, if it’s negative, to be less than or equal to 1.

@rockowd Also, can you attach the figure generated by the last step of your code (I don’t know what `infile` you’re using).

**Comment by rockowd** [comment]
Thank you very much for the explanation, it helped a lot. I am still a little confused about the "interval_length". Is interval length just the values from the Jacobian matrix?

![forissue](https://user-images.githubusercontent.com/52171850/63115544-3ccd0680-bf4c-11e9-8d3f-81f72b50dfa1.png)
Above is a figure generated when b was -0.25 for the (1,1) entry. I am currently unable to generate all the figures because with the code 
`GenerateEntryWiseFigures(EntryWise=Entrywise2, all_numswitch_plots = TRUE)`
I get the following error
`Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed`
I am still working to determine how to resolve this issue. The infile I am currently using is a network I created with ten species and a directed conductance of 0.25.

**Comment by dkoslicki** [comment]
@rockowd apologies for the delayed reply. The "interval_length" is the length of the interval of asymptotic stability for the matrix. I.e. what the acceptable values perturbation values are that still lead to a matrix with all negative (real part) eigenvalues. If you send me the matrix that is giving the `GenerateEntryWiseFigures` issues, I can try to help diagnose it.

**Comment by marknovak** [comment]
I believe he figured this out, so closing.
