### ISSUE TITLE
tsv -> csv

### ISSUE THREAD

**Issue by marknovak** [dkoslicki/PressPurtCoreAlg#6]
Resave Wildermuth as csv files

**Comment by dkoslicki** [comment]
And just so you're aware: you've been saving files with dos line endings (the '^M' character) instead of unix line endings '$' or '\n'. I've just run [dos2unix](https://linux.die.net/man/1/dos2unix) on all the matrices you uploaded and that resolved the issue. But if in the future you see a parsing error, this is probably the culprit.

**Comment by marknovak** [comment]
Resaved as csv and with different encoding (though I'm not sure what encoding it actually is...MS Excel doesn't indicate).  The prior (Excel default) that I used was apparently UTF 8.  Let me know if the four Windermuth files need a different encoding.  (This will of course also be an issue if I edit/resave any of the existing files.  The only other csv encoding option I can see within Excel is MS-DOS.)

**Comment by dkoslicki** [comment]
The matrix `Wildermuth2017_ComplexDetailed.csv` is not stable, nor is `Wildermuth2017_ComplexReduced.csv`
The "Simple" version are stable and appear to work just fine. @marknovak I vote we remove the two complex wildermuth examples since they aren't stable.

**Comment by dkoslicki** [comment]
Closing and continuing the related discussion at #5
